-- =============================================================
-- Roles / RBAC + admin question authoring
-- Multi-role per user via a dedicated user_roles table.
-- Add new roles later with:  alter type public.app_role add value 'super_user';
-- =============================================================

create type public.app_role as enum ('admin');

create table public.user_roles (
  id bigint generated by default as identity not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  role public.app_role not null,
  created_at timestamp with time zone not null default now(),
  constraint user_roles_pkey primary key (id),
  constraint user_roles_user_role_unique unique (user_id, role)
);

alter table public.user_roles enable row level security;

-- A user may read their own roles; writes happen only via the
-- service role / SQL (no insert/update/delete policy = client blocked).
create policy "read own roles" on public.user_roles for select
  to authenticated
  using (user_id = auth.uid());

-- -------------------------------------------------------------
-- Helpers. SECURITY DEFINER so the check bypasses user_roles' own
-- RLS (avoids recursion) and works when called via RPC from the app.
-- -------------------------------------------------------------
create or replace function public.has_role(_role public.app_role)
  returns boolean
  language sql
  security definer
  stable
  set search_path = public
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = auth.uid() and role = _role
  );
$$;

create or replace function public.is_admin()
  returns boolean
  language sql
  security definer
  stable
  set search_path = public
as $$
  -- Broaden later, e.g. select public.has_role('admin') or public.has_role('super_user');
  select public.has_role('admin');
$$;

-- -------------------------------------------------------------
-- Canonical question types (idempotent seed). The form sets
-- questions.type_id by looking these up by name.
-- -------------------------------------------------------------
create unique index if not exists question_types_type_key
  on public.question_types (type);

insert into public.question_types (type)
values ('yes/no'), ('over/under')
on conflict (type) do nothing;

-- -------------------------------------------------------------
-- Question authoring: admins may insert questions and their lines.
-- (public read policies already exist from the initial schema)
-- Future queue: a public-submission policy will insert with a
-- 'pending' status instead; these admin policies stay as the
-- no-review path.
-- -------------------------------------------------------------
create policy "admins insert questions" on public.questions for insert
  to authenticated
  with check (public.is_admin());

create policy "admins insert lines" on public.lines for insert
  to authenticated
  with check (public.is_admin());
