

create table public.question_types (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  type text null,
  constraint question_types_pkey primary key (id)
) TABLESPACE pg_default;

create table public.questions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  question text null default ''::text,
  type_id bigint null,
  enabled boolean null,
  constraint questions_pkey primary key (id),
  constraint questions_id_key unique (id),
  constraint questions_type_id_fkey foreign KEY (type_id) references question_types (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.lines (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  question_id bigint not null,
  line text null,
  constraint lines_pkey primary key (id),
  constraint lines_question_id_fkey foreign KEY (question_id) references questions (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.answers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null references auth.users(id),
  answer boolean not null default false,
  question_id bigint not null,
  constraint answers_pkey primary key (id),
  constraint answers_question_id_fkey foreign KEY (question_id) references questions (id) on update CASCADE on delete CASCADE,
  constraint answers_user_question_unique unique (user_id, question_id)
) TABLESPACE pg_default;

-- Row Level Security
alter table public.questions enable row level security;
alter table public.lines enable row level security;
alter table public.answers enable row level security;

create policy "public read" on public.questions for select using (true);
create policy "public read" on public.lines for select using (true);
create policy "public read" on public.answers for select using (true);

create policy "authenticated insert" on public.answers for insert
  to authenticated
  with check (auth.uid() = user_id);
